# Generated by Django 3.2.11 on 2022-01-08 05:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beautyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addduration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Addprice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Addstaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('mobileno', models.CharField(max_length=12)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beautyapp.citys')),
            ],
        ),
        migrations.CreateModel(
            name='Paymentmod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('gname', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=100)),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField()),
                ('price', models.CharField(max_length=50)),
                ('comments', models.CharField(blank=True, default='NA', max_length=500, null=True)),
                ('out', models.BooleanField(default=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beautyapp.citys')),
                ('duration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.addduration')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.paymentmod')),
                ('services', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beautyapp.services')),
                ('treatment_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.addstaff')),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('particular', models.CharField(max_length=250)),
                ('bill_no', models.CharField(default='none', max_length=400)),
                ('amount', models.CharField(max_length=50)),
                ('remarks', models.CharField(max_length=250)),
                ('reciept', models.ImageField(blank=True, null=True, upload_to='Images/expenses/')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beautyapp.citys')),
            ],
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('time_in', models.TimeField(blank=True, null=True)),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('remarks', models.CharField(default='present', max_length=250)),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.addstaff')),
            ],
        ),
    ]
